### ISSUE TITLE
如何在播放器自定义按钮控件？

### ISSUE THREAD

**Issue by RaccoonSmall** [muiplayer/hello-muiplayer#1]

**Comment by muiplayer** [comment]
Mui Player 支持自定义播放器头部，底部控件以及弹出的右侧栏窗口，具体使用参考：https://muiplayer.js.org/zh/custom-control/

**Comment by sdcdn** [comment]
请问怎么整合到WordPress，我试了一下没有成功！

**Comment by sdcdn** [comment]
`    <script type="text/javascript">
      // 初始化 MuiPlayer 插件，MuiPlayer 方法传递一个对象，该对象包括所有插件的配置
     var mp = new MuiPlayer({
     container:document.getElementById("mui-player"),
        width: "100%",
        height: "100%",
        title: "{$obj.type_name}",
        src:"<?php echo $_GET['url'];?>",
		live: false,
		themeColor:'#ff142b', // 自定义主题颜色
		//hls播放器控件
		parse:{
		    type:'hls',
		    loader:Hls,
		    config:{ // hls config to：https://github.com/video-dev/hls.js/blob/HEAD/docs/API.md#fine-tuning
		        debug:false,
		    },
		},
        plugins: [
          new MuiPlayerDesktopPlugin({
            contextmenu: [
              {
                name: "muiplayer",
                context: "播放器",
                zIndex: 0,
                show: true,
                click: function (close) {
                  // Action...
                },
              },
            ],
          }),
        ],
});
    </script>`
