### ISSUE TITLE
请问现在下载的为啥没有移动端插件了？

### ISSUE THREAD

**Issue by cqsn558** [muiplayer/hello-muiplayer#10]
以前在release目录里有移动端插件，现在为啥没有了？

**Comment by jessibuca** [comment]
>> 关于移动端插件
关于移动端插件请下载专业版本：https://muiplayer.js.org/zh/joinUs/#%E4%B8%93%E4%B8%9A%E7%89%88%E6%8F%92%E4%BB%B6

缘由：开源是一件非常困难的事情，在考虑所有人特定场景的需求以及在设计、研发、API规划等整个产品的生命周期需要花费大量的时间，但是开源版我们依然提供稳定的视频播放解决方案，而专业版在于真正的服务于市场，专业版将会得到官方直接的开发和技术支持，感谢您的使用和支持~
