### ISSUE TITLE
how to play live http-flv media?

### ISSUE THREAD

**Issue by tony7tony** [muiplayer/hello-muiplayer#12]
code:

var mp = new MuiPlayer({
    container:document.getElementById("mui-player"),
    src:'http://192.168.1.10:8080/live/stream.flv',
    parse:{
        type:'flv',
        loader:Flv,
        config:{
            isLive:true,
            withCredentials:false,
            cors:true,
        },
    },
});

but can't play..

**Comment by muiplayer** [comment]
Please check media and code.

**Comment by tony7tony** [comment]
ffmpeg.exe -re -stream_loop -1 -i demo.mp4 -c copy -f flv rtmp://192.168.1.10:1935/live/stream

use ffmpeg to push flow

**Comment by tony7tony** [comment]
<script>
// 示例 hls 配置
var mp = new MuiPlayer({
    container:document.getElementById("mui-player"),
    src:'http://192.168.1.10:8080/live/stream.m3u8',
    title: '演示视频',
    width:'50%',
    parse:{
        type:'hls',
        loader:Hls,
        // hls config to：https://github.com/video-dev/hls.js/blob/HEAD/docs/API.md#fine-tuning
        config:{
            debug:false,
        },
    },
});
</script>

test hls，it works, just desktop plugin button disappear

**Comment by muiplayer** [comment]
https://muiplayer.js.org/zh/guide/preset.html#配置
