### ISSUE TITLE
autoplay无效

### ISSUE THREAD

**Issue by lixiusen** [muiplayer/hello-muiplayer#13]
var playerConfig = {
            container:'#mui-player',
            autoplay: true,
            src:'https://muiplayer.oss-cn-shanghai.aliyuncs.com/static/media/media.mp4',
            videoAttribute:[
                {attrKey:'webkit-playsinline',attrValue:''},
                {attrKey:'playsinline',attrValue:''},
                {attrKey:'x5-playsinline',attrValue:''},
                {attrKey:'t7-video-player-type',attrValue:'inline'},
                {attrKey:'x5-video-player-type',attrValue:'h5-page'},
                {attrKey:'x-webkit-airplay',attrValue:'allow'},
                {attrKey:'controlslist',attrValue:'nodownload'},
            ],
        }

**Comment by muiplayer** [comment]
>  关于视频自动播放 autoplay 属性设置问题？

**请参考：**
https://muiplayer.js.org/zh/guide/other-problem.html#视频自动播放-autoplay-属性设置问题
