### ISSUE TITLE
如何停止m3u8直播的请求

### ISSUE THREAD

**Issue by EmiyaGm** [muiplayer/hello-muiplayer#16]
销毁播放器后，仍然在不停的请求

**Comment by muiplayer** [comment]
您好，请问你 mui-player.min.js 使用的版本号是多少？请更新到最新版本后尝试：
https://www.npmjs.com/package/mui-player

**Comment by EmiyaGm** [comment]
> 您好，请问你 mui-player.min.js 使用的版本号是多少？请更新到最新版本后尝试： https://www.npmjs.com/package/mui-player

确定是最新的1.5.0版本，是不是 video 在 destroy 之后，用来解析的 hls 没有销毁

```javascripte
// 这是我的配置，还额外用 hls.js 来解析 m3u8 的直播
mp.value = new MuiPlayer({
        container: '#mui-player',
        title,
        src: url,
        width: 'auto',
        height: 'auto',
        live: true,
        autoplay: true,
        poster,
        parse: {
          type: 'hls',
          loader: Hls,
          config: {
            debug: false,
          },
        },
      });
```

**Comment by muiplayer** [comment]
方法：mp.value.destory();

经过地址：http://cctvtxyh5c.liveplay.myqcloud.com/live/cdrmcctv2_1/index.m3u8 测试有效。

**Comment by muiplayer** [comment]
Thank, the bug has been repair, please update to version 1.6.0。
https://www.npmjs.com/package/mui-player/v/1.6.0

**Comment by EmiyaGm** [comment]
> Thank, the bug has been repair, please update to version 1.6.0。 https://www.npmjs.com/package/mui-player/v/1.6.0

我试了一下，新版本的destroy确实可以停止m3u8的直播了，但是有了一个新问题是，autoplay自动播放的配置不起作用了，直播一开始处于暂停的情况，但是m3u8的请求倒是一直在走

**Comment by EmiyaGm** [comment]
> > Thank, the bug has been repair, please update to version 1.6.0。 https://www.npmjs.com/package/mui-player/v/1.6.0
> 
> 我试了一下，新版本的destroy确实可以停止m3u8的直播了，但是有了一个新问题是，autoplay自动播放的配置不起作用了，直播一开始处于暂停的情况，但是m3u8的请求倒是一直在走

找到问题了，是因为 Chrome 自动播放政策的原因，设置成静音之后就可以了。
