### ISSUE TITLE
请问怎么整合到WordPress，我试了一下没有成功！

### ISSUE THREAD

**Issue by sdcdn** [muiplayer/hello-muiplayer#2]
简单写了一下，没成功

**Comment by muiplayer** [comment]
哪里报错了吗？请控制台输出看一下播放器配置对象以及检查一下配置标签是否正确。

**Comment by sdcdn** [comment]
已经弄好了

**Comment by sdcdn** [comment]
播放器mp4和m3u8还要单独调用，这就尴尬了[https://bj.bcebos.com/im-cs/313470536c52c9c1bfe5276db81c2384.jpg](url)

**Comment by muiplayer** [comment]
@
