### ISSUE TITLE
视频高度

### ISSUE THREAD

**Issue by yunfeng-Harris** [muiplayer/hello-muiplayer#20]
`
我在加载flv的时候，包裹video的div.m-player容器为什么会自动设置style中的高度和宽度，导致页面加载视频的时候高度在变化？
`

**Comment by muiplayer** [comment]
请问您是引用了视频字幕了吗？

**Comment by yunfeng-Harris** [comment]
没有引用视频字幕，用了flv加载

**Comment by muiplayer** [comment]
请您仔细阅读文档 API 描述：https://muiplayer.js.org/zh/guide/api.html#主要配置
注意配置参数：width、height、autoFit
