### ISSUE TITLE
播放m3u8报错 在微信中可以播放 pc chrome报错

### ISSUE THREAD

**Issue by RedShameA** [muiplayer/hello-muiplayer#23]
[system] hlsError  at node_modules/mui-player/dist/mui-player.min.js:7
（匿名） @ chunk-vendors.c478791f.js:7
a @ chunk-vendors.c478791f.js:1
onError @ pages-sale-video-video.eb974dff.js:7
u.emit @ pages-sale-video-video.eb974dff.js:11
t.emit @ pages-sale-video-video.eb974dff.js:199
t.trigger @ pages-sale-video-video.eb974dff.js:199
m.onerror @ pages-sale-video-video.eb974dff.js:175
error（异步）
e @ pages-sale-video-video.eb974dff.js:175
r._handleFragmentLoadProgress @ pages-sale-video-video.eb974dff.js:99
n @ pages-sale-video-video.eb974dff.js:43
onProgress @ pages-sale-video-video.eb974dff.js:207
t.readystatechange @ pages-sale-video-video.eb974dff.js:371
XMLHttpRequest.send（异步）
t.loadInternal @ pages-sale-video-video.eb974dff.js:371
t.load @ pages-sale-video-video.eb974dff.js:371
（匿名） @ pages-sale-video-video.eb974dff.js:207
t.load @ pages-sale-video-video.eb974dff.js:207
r._doFragLoad @ pages-sale-video-video.eb974dff.js:43
r._loadFragForPlayback @ pages-sale-video-video.eb974dff.js:43
r.loadFragment @ pages-sale-video-video.eb974dff.js:43
r.loadFragment @ pages-sale-video-video.eb974dff.js:99
r.doTickIdle @ pages-sale-video-video.eb974dff.js:99
r.doTick @ pages-sale-video-video.eb974dff.js:99
t.tick @ pages-sale-video-video.eb974dff.js:259
r.onLevelLoaded @ pages-sale-video-video.eb974dff.js:99
u.emit @ pages-sale-video-video.eb974dff.js:11
t.emit @ pages-sale-video-video.eb974dff.js:199
t.trigger @ pages-sale-video-video.eb974dff.js:199
t.handlePlaylistLoaded @ pages-sale-video-video.eb974dff.js:235
t.handleTrackOrLevelPlaylist @ pages-sale-video-video.eb974dff.js:235
t.loadsuccess @ pages-sale-video-video.eb974dff.js:235
t.readystatechange @ pages-sale-video-video.eb974dff.js:371
XMLHttpRequest.send（异步）
t.loadInternal @ pages-sale-video-video.eb974dff.js:371
t.load @ pages-sale-video-video.eb974dff.js:371
t.load @ pages-sale-video-video.eb974dff.js:235
t.onManifestLoading @ pages-sale-video-video.eb974dff.js:235
u.emit @ pages-sale-video-video.eb974dff.js:11
t.emit @ pages-sale-video-video.eb974dff.js:199
t.trigger @ pages-sale-video-video.eb974dff.js:199
t.loadSource @ pages-sale-video-video.eb974dff.js:199
（匿名） @ pages-sale-video-video.eb974dff.js:7
u.emit @ pages-sale-video-video.eb974dff.js:11
t.emit @ pages-sale-video-video.eb974dff.js:199
t.trigger @ pages-sale-video-video.eb974dff.js:199
_onMediaSourceOpen @ pages-sale-video-video.eb974dff.js:47

**Comment by muiplayer** [comment]
Api：
https://muiplayer.js.org/zh/guide/preset.html

Example：
https://github.com/muiplayer/hello-muiplayer/blob/master/demo/hlsExample.html

**Comment by RedShameA** [comment]
> Api： https://muiplayer.js.org/zh/guide/preset.html
> 
> Example： https://github.com/muiplayer/hello-muiplayer/blob/master/demo/hlsExample.html

感谢开发者回复，Hls插件已经引入，微信端可以成功播放m3u8视频了，但是PC chrome不知道为何无法播放，我只能看到那一段报错，正在打开Hls的debug模式，有新信息了会贴上来

**Comment by RedShameA** [comment]
还同时有这样一段错误，不知道有没有参考价值

Uncaught ReferenceError: i is not defined
    at e.t.remuxVideo (02693482-6238-46b9-9a6e-8d6ceda3a1d2:1:38154)
    at e.t.remux (02693482-6238-46b9-9a6e-8d6ceda3a1d2:1:34181)
    at e.t.flushRemux (02693482-6238-46b9-9a6e-8d6ceda3a1d2:1:11943)
    at e.t.flush (02693482-6238-46b9-9a6e-8d6ceda3a1d2:1:11639)
    at 02693482-6238-46b9-9a6e-8d6ceda3a1d2:1:1661

**Comment by RedShameA** [comment]
解决了... 是开启了HBuilderX Manifest.json h5 配置中的摇树优化导致的...
