### ISSUE TITLE
如何监听 hls 的 error 事件

### ISSUE THREAD

**Issue by Artwinter** [muiplayer/hello-muiplayer#27]

**Comment by muiplayer** [comment]
> 如何监听 hls 的 error 事件

一、Mui Player 提供了部分事件监听动动作，可通过 on 方法添加 error 事件监听，接收为原生事件的回调参数，参考：
[https://muiplayer.js.org/zh/guide/api.html#播放事件监听](https://muiplayer.js.org/zh/guide/api.html#播放事件监听)

二：通过自定义使用的 MSE 编解码库，主动添加播放错误事件。参考：
[https://muiplayer.js.org/zh/guide/preset.html#自定义使用mse库](https://muiplayer.js.org/zh/guide/preset.html#自定义使用mse库)
