### ISSUE TITLE
播放器mp4和m3u8还要单独调用，这就尴尬了[https://bj.bcebos.com/im-cs/313470536c52c9c1bfe5276db81c2384.jpg](url)

### ISSUE THREAD

**Issue by muiplayer** [muiplayer/hello-muiplayer#3]
播放器mp4和m3u8还要单独调用，这就尴尬了[https://bj.bcebos.com/im-cs/313470536c52c9c1bfe5276db81c2384.jpg](url)

_Originally posted by @sdcdn in https://github.com/muiplayer/hello-muiplayer/issues/2#issuecomment-830626820_

创建播放器动态配置 parse，或者自定义使用 MSE 库的：https://muiplayer.js.org/zh/guide/preset.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BD%BF%E7%94%A8mse%E5%BA%93

**Comment by sdcdn** [comment]
如果可以的话在官网贴一个演示代码，这样好参考，我看现在的演示都是都看不到代码怎么写的

**Comment by muiplayer** [comment]
目前建议多看看熟悉一下 API 配置文档，后期会考虑添加代码在线编辑及演示，请关注 MuiPlayer。
