### ISSUE TITLE
Mui-Player 如何需改标题

### ISSUE THREAD

**Issue by SextupleStar** [muiplayer/hello-muiplayer#30]
官方文档中只有重新加载视频地址的接口 reloadUrl，并没有修改其左上角标题的接口，虽然可以通过 document.getElementById("title-name").innerHTML = '标题'; 来修改。

**Comment by muiplayer** [comment]
使用 innerHTML  来修改 title，利用 getControls() 获取播放器所有控件；

**Comment by SextupleStar** [comment]
> 使用 innerHTML 来修改 title，利用 getControls() 获取播放器所有控件；

好的，谢谢

**Comment by woshi007** [comment]
reloadUrl()之后，播放记忆时间还是初始化的记忆时间，这个怎么修改呢
