### ISSUE TITLE
怎么关闭网页全屏按钮啊

### ISSUE THREAD

**Issue by xxcms** [muiplayer/hello-muiplayer#31]
怎么关闭网页全屏按钮啊 我找了几个小时配置了

**Comment by muiplayer** [comment]
> 关闭网页全屏按钮

Mui Player 并不包含所有控件可直接配置状态的 API，自定义化要求 “关闭网页全屏” 按钮等可通过播放器接口 getControls() 获取指定的控件进行 dom 操作。

**Comment by xxcms** [comment]
我买了你的移动版的了，因为我是嵌入在iframe里面的 所以网页全屏就需要关闭他

**Comment by xxcms** [comment]
我以为这个肯定是有参数可以配置的，找了2个小时都没找到这个配置，那意思直接 $("#pagefull-switch").remove(); 就完事了啊
