### ISSUE TITLE
倍速播放菜单显示有问题？

### ISSUE THREAD

**Issue by rwshui** [muiplayer/hello-muiplayer#4]
选择了非正常速度播放后，退出菜单，再次进入速度设置，显示为正常而非当前实际播放速度。
另外，VTT字幕与底部的距离如何调节？

**Comment by muiplayer** [comment]
![menu](https://user-images.githubusercontent.com/77326133/118201208-7d6df280-b446-11eb-9ea8-b3887592fd80.png)
暂未发现倍速播放菜单问题，你可以加入社群向继续向反馈该问题。

从这里查看 [VTT字幕](https://developer.mozilla.org/zh-CN/docs/Web/Guide/Audio_and_video_delivery/Adding_captions_and_subtitles_to_HTML5_video#%E4%B8%BA%E5%AD%97%E5%B9%95%E6%B7%BB%E5%8A%A0%E6%A0%B7%E5%BC%8F) 支持使用的样式

**Comment by muiplayer** [comment]
![menu15](https://user-images.githubusercontent.com/77326133/118201910-2832e080-b448-11eb-977a-7a475a3d75e1.png)
暂未发现倍速播放菜单问题，你可以加入社群向继续向反馈该问题。

从这里查看 [VTT字幕](https://developer.mozilla.org/zh-CN/docs/Web/Guide/Audio_and_video_delivery/Adding_captions_and_subtitles_to_HTML5_video#%E4%B8%BA%E5%AD%97%E5%B9%95%E6%B7%BB%E5%8A%A0%E6%A0%B7%E5%BC%8F) 支持使用的样式

**Comment by rwshui** [comment]
我尝试的是PC端的演示页
[WIN10 EDGE浏览器 官方演示页](https://files.catbox.moe/g4udzr.mp4)

**Comment by muiplayer** [comment]
> 倍速播放菜单显示有问题？

好的，感谢你反馈的这个问题~  
**mui-player-desktop-plugin 1.3.1** 的版本将修复此问题！

**Comment by muiplayer** [comment]
已修复 pc 端菜单组选择显式问题，请更新到 **mui-player-desktop-plugin 1.3.1** 版本！
