### ISSUE TITLE
关于播放器的两个需求

### ISSUE THREAD

**Issue by netsesame2** [muiplayer/hello-muiplayer#7]
正在项目中使用这个播放器，比较满意。以下两个需求我通过额外的代码实现，但如果能整合进代码会更完美：
1、H5播放前，能否在视频正中显示一个播放按钮。点击播放按钮后，视频开始播放
2、头部的标题区域能否设置隐藏

**Comment by muiplayer** [comment]
1. 个性化的场景还是需要自己手动去实现
2. 针对头部的标题区域能否设置隐藏，有个自定义属性：pageHead 提供使用。你可以通过 getControls 接口去获取头元素实现隐藏
