### ISSUE TITLE
全屏时画面被显示不全

### ISSUE THREAD

**Issue by liangchanglong** [muiplayer/hello-muiplayer#8]
![image](https://user-images.githubusercontent.com/18343229/122141215-6bd19d80-ce7f-11eb-8b0c-b7ee3c4e91c6.png)
![image](https://user-images.githubusercontent.com/18343229/122141237-7c821380-ce7f-11eb-8966-3ecd7be1a7a7.png)
画面上下各被裁掉部分
环境：
huawei P30Pro
Android 10
EMUI 11.0.0

**Comment by liangchanglong** [comment]
尝试了修改autoFit属性，全屏播放时依然没有变化，从表现上看因为手机屏幕较长，全屏时width适应了屏幕宽度，height根据视频尺寸比例调整，超出了我手机屏幕的高度，导致一部分无法显示出来。手机插件中铺满屏幕开关状态切换，也没有对视频比例做拉伸。请问是否有相关配置可以自适应全屏状态，拉伸或者增加黑边均可，视频内容应该全部显示

**Comment by cqsn558** [comment]
我的手机与楼主一样，也是华为P30Pro，测试同样出现上下被裁掉的问题，准确来说是视频的上下超出了屏幕上下。我用其他手机和一些视频测试了一下，应该就是这款手机比有些手机屏幕要长，我网上查了下，这款手机长宽比是19.5：6，而一般的手机长宽比是16：9。通过对一些视频的比较，用一般长宽比为16：9的手机全屏播放窄屏视频时上下也会超出屏幕，演示站因为用的是宽屏视频，16：9的手机全屏不容易看出来。我试着用16：9的手机以及作者的演示代码播放窄屏视频，同样会出现这种情况，而且播放窄屏视频上下超出屏幕更严重，更容易看出来，因此基本可以肯定应该是播放器代码的bug，并不是对播放器设置上的错误。另外在电脑上播放窄屏视频并全屏时(包括网页全屏和屏幕全屏)，上下也超出边界。其他播放器处理的办法是窄屏视频在两边加黑边(不建议拉伸，容易造成影像变形)。在这里我也非常感谢作者提供了一款很好的播放器，希望这款播放器越做越好。下面附上我搭建的测试网址供作者测试，我除了把视频链接改为窄屏的链接外，其他没有任何修改。视频链接可能有点慢，请稍微等待一下。
https://www.paopaomj.com/code/demo/hlsExample.html

**Comment by muiplayer** [comment]
> 关于视频按比例播放画面被裁剪的问题！

感谢 @cqsn558 @liangchanglong 的分享和建议， mui-player v1.5.0 将修复此问题。请等待更新…

**Comment by muiplayer** [comment]
>> 关于视频按比例播放画面被裁剪的问题！
新版本已修复，请更新至最新版：mui-player、mui-player-desktop-plugin
